defmodule Cineaste.Repo.Migrations.AddAdditionalFilmFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:films) do
      add :original_title, :text
      add :original_title_translation, :text
      add :original_title_transliteration, :text
      add :poster_url, :text
    end
  end

  def down do
    alter table(:films) do
      remove :poster_url
      remove :original_title_transliteration
      remove :original_title_translation
      remove :original_title
    end
  end
end
