defmodule Cineaste.Repo.Migrations.TweakFilmAliasReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:film_aliases, "film_aliases_film_id_fkey")

    alter table(:film_aliases) do
      modify :film_id,
             references(:films,
               column: :id,
               name: "film_aliases_film_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:film_aliases, "film_aliases_film_id_fkey")

    alter table(:film_aliases) do
      modify :film_id,
             references(:films,
               column: :id,
               name: "film_aliases_film_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
