defmodule Cineaste.Repo.Migrations.TweakFilmStudiosPk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("film_studios", "film_studios_pkey")

    alter table(:film_studios) do
      modify :studio_id, :uuid
      modify :film_id, :uuid
    end

    drop_if_exists unique_index(:film_studios, [:film_id, :studio_id],
                     name: "film_studios_unique_studio_per_film_index"
                   )

    execute("ALTER TABLE \"film_studios\" ADD PRIMARY KEY (id, film_id, studio_id)")
  end

  def down do
    drop constraint("film_studios", "film_studios_pkey")

    create unique_index(:film_studios, [:film_id, :studio_id],
             name: "film_studios_unique_studio_per_film_index"
           )

    alter table(:film_studios) do
      modify :film_id, :uuid
      modify :studio_id, :uuid
    end

    execute("ALTER TABLE \"film_studios\" ADD PRIMARY KEY (id)")
  end
end
