defmodule Cineaste.Repo.Migrations.AddPeopleResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:people, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :display_name, :text, null: false
      add :sort_name, :text
      add :showcased, :boolean, default: false
      add :disambig_chars, :text
      add :profession, :text
      add :avatar_url, :text
      add :dob, :date
      add :dob_resolution, :text
      add :birth_place, :text
      add :dod, :date
      add :dod_resolution, :text
      add :death_place, :text
      add :cause_of_death, :text
      add :japanese_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:people, [:slug], name: "people_unique_slug_per_person_index")
  end

  def down do
    drop_if_exists unique_index(:people, [:slug], name: "people_unique_slug_per_person_index")

    drop table(:people)
  end
end
