defmodule Cineaste.Repo.Migrations.AddFilmAliases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:films) do
      add :aliases, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:films) do
      remove :aliases
    end
  end
end
