defmodule Cineaste.Repo.Migrations.TweakFilmStudiosAgain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("film_studios", "film_studios_pkey")

    alter table(:film_studios) do
      remove :updated_at
      remove :inserted_at
      remove :id
    end

    execute("ALTER TABLE \"film_studios\" ADD PRIMARY KEY (film_id, studio_id)")
  end

  def down do
    alter table(:film_studios) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute("ALTER TABLE \"film_studios\" DROP constraint film_studios_pkey")

    execute("ALTER TABLE \"film_studios\" ADD PRIMARY KEY (id, film_id, studio_id)")
  end
end
