defmodule Cineaste.Repo.Migrations.AddFilms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:films, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :title, :text, null: false
      add :release_date, :date, null: false
      add :runtime, :bigint
      add :showcased, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:films, [:slug], name: "films_unique_slug_per_film_index")
  end

  def down do
    drop_if_exists unique_index(:films, [:slug], name: "films_unique_slug_per_film_index")

    drop table(:films)
  end
end
