defmodule Cineaste.Repo.Migrations.RenameOrderFieldOnFilmSeriesEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:film_series_entries), :entry_number, to: :order

    drop constraint(:film_series_entries, "film_series_entries_film_series_id_fkey")

    drop constraint(:film_series_entries, "film_series_entries_film_id_fkey")

    alter table(:film_series_entries) do
      modify :film_id,
             references(:films,
               column: :id,
               name: "film_series_entries_film_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :film_series_id,
             references(:film_series,
               column: :id,
               name: "film_series_entries_film_series_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:film_series_entries, "film_series_entries_film_id_fkey")

    drop constraint(:film_series_entries, "film_series_entries_film_series_id_fkey")

    alter table(:film_series_entries) do
      modify :film_series_id,
             references(:film_series,
               column: :id,
               name: "film_series_entries_film_series_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :film_id,
             references(:films,
               column: :id,
               name: "film_series_entries_film_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:film_series_entries), :order, to: :entry_number
  end
end
